spring.application.name=demo2

MONGODB_USERNAME=sultan2793_db_user

MONGODB_PASSWORD=occ53STpt9TBNSlx

MONGODB_URI=mongodb+srv://sultan2793_db_user:occ53STpt9TBNSlx@cluster0.hyvnh4z.mongodb.net
spring.data.mongodb.uri=${MONGODB_URI}/demo?appName=Cluster0
spring.data.mongodb.username=${MONGODB_USERNAME}

spring.data.mongodb.password=${MONGODB_PASSWORD}

